[BACKLOG-38691] - Create and Add Tree Map Visualization to the available list of Chart options in Analyzer
webdetails/cgg pull request #170
Opened 2023-11-03 11:20 UTC by phalguni-a

RequireJs configuration from #https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1709

2023-11-03 16:48 UTC, dcleao requested changes

2023-11-03 16:48 UTC, dcleao commented on core/src/main/javascript/pt/webdetails/cgg/resources/define-cfg.js
> +        "pentaho/visual/models/types/LayoutMode",
Did not update changed name.

2023-11-04 07:40 UTC, buildguy commented
### :warning: Build finished in 3m 22s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>pt.webdetails.cgg.CggGoldSampleTest.testExecuteReports</b> (click to expand)</summary><p>

```
Failed at /build/wingman/workspace/maintenance/wingman/builds/webdetails.cgg.PR-170/core/target/test-classes/test-gold/cgg/sample1/cccRaw-svg-test.js
```

</p></details>

  
Tests run: **2**, Failures: **1**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/cgg-plugin/job/PR-170/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-11-06 23:19 UTC, dcleao approved these changes

2023-11-07 08:40 UTC, buildguy commented
### :warning: Build finished in 3m 15s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>pt.webdetails.cgg.CggGoldSampleTest.testExecuteReports</b> (click to expand)</summary><p>

```
Failed at /build/wingman/workspace/maintenance/wingman/builds/webdetails.cgg.PR-170/core/target/test-classes/test-gold/cgg/sample1/cccRaw-svg-test.js
```

</p></details>

  
Tests run: **2**, Failures: **1**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/cgg-plugin/job/PR-170/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-11-08 07:49 UTC, buildguy commented
### :white_check_mark: Build finished in 12m 20s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **2**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/cgg-plugin/job/PR-170/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-11-08 13:52 UTC, closed without merging