[BACKLOG-38921] Add Stacked-Line Chart
webdetails/cgg pull request #174
Opened 2023-11-09 12:51 UTC by AAravind27

2023-11-10 08:40 UTC, buildguy commented
### :white_check_mark: Build finished in 3m 46s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **2**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/cgg-plugin/job/PR-174/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-11-17 13:59 UTC, dcleao requested changes

2023-11-17 13:59 UTC, dcleao commented on core/src/main/javascript/pt/webdetails/cgg/resources/define-cfg.js
> +        "pentaho/visual/visual/LineStacked",
`pentaho/ccc/visual/LineStacked`

2023-11-17 15:22 UTC, dcleao approved these changes

2023-11-18 08:43 UTC, buildguy commented
### :white_check_mark: Build finished in 6m 21s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **2**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/cgg-plugin/job/PR-174/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-11-20 08:42 UTC, buildguy commented
### :white_check_mark: Build finished in 5m 44s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **2**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/cgg-plugin/job/PR-174/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-11-22 15:55 UTC, merged